# Generated by Django 4.2.1 on 2023-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post_list",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20, verbose_name="제목")),
                ("author", models.CharField(max_length=10, verbose_name="작성자")),
                ("content", models.CharField(max_length=100, verbose_name="내용")),
            ],
        ),
    ]
